sudo: true
dist: trusty
language: python
python:
  - '3.5'
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
jobs:
  include:
    - stage: build docker image
      script:
      - docker --version
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t hspc-django .
      - docker images
      - docker tag hspc-django $DOCKER_USERNAME/hspc-django
      - docker push $DOCKER_USERNAME/hspc-django
