# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuentry',
            options={'verbose_name_plural': 'Menu Entries'},
        ),
        migrations.AddField(
            model_name='menuentry',
            name='is_divider',
            field=models.BooleanField(default=False),
        ),
    ]
