# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='body',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='title',
            new_name='hidden_label',
        ),
        migrations.RenameField(
            model_name='newsmention',
            old_name='display_text',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='newsmention',
            old_name='title',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='newsmention',
            name='created',
        ),
        migrations.AddField(
            model_name='newsmention',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
