# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170522_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuentry',
            name='top_level_name',
            field=models.CharField(blank=True, help_text='Only used if this is a top-level menu entry', max_length=128, null=True),
        ),
    ]
