# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171023_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField((('homepage_panel', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('material_icon_name', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.TextBlock()), ('link_url', wagtail.core.blocks.URLBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_is_external', wagtail.core.blocks.BooleanBlock(required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('overlay_css_background_color', wagtail.core.blocks.CharBlock())))),), blank=True),
        ),
    ]
