# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsmention_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('homepage_panel', wagtail.wagtailcore.blocks.StructBlock((('material_icon_name', wagtail.wagtailcore.blocks.CharBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock()), ('caption_text', wagtail.wagtailcore.blocks.TextBlock()), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('overlay_css_background_color', wagtail.wagtailcore.blocks.CharBlock())))),)),
        ),
    ]
