# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171022_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='collaboration_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='marketplace_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='membership_text',
        ),
    ]
