# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_menuentry_top_level_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuentry',
            options={'ordering': ['order'], 'verbose_name_plural': 'Menu Entries'},
        ),
    ]
