# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('website', '0006_auto_20170524_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('mainmenuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailmenus.MainMenuItem')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ('sort_order',),
                'abstract': False,
            },
            bases=('wagtailmenus.mainmenuitem',),
        ),
    ]
