# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170525_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_location',
            new_name='location',
        ),
    ]
