# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170525_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='page_title',
        ),
    ]
