# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170525_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=64)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
