# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.blocks.static_block
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20170807_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'event categories'},
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='hidden_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Used to sort events', verbose_name='sortable date'),
        ),
        migrations.AlterField(
            model_name='robustinfopage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('separator', wagtail.wagtailcore.blocks.static_block.StaticBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))),
        ),
        migrations.AlterField(
            model_name='robustinfopage',
            name='date',
            field=models.DateField(verbose_name='Last updated'),
        ),
    ]
